sudo: required
services:
  - docker

before_install:
  - docker build -t amrit/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run amrit/react-test npm test -- --coverage
after_success:
  - docker build -t amrit/multi-client ./client
  - docker build -t amrit/multi-nginx ./nginx
  - docker build -t amrit/multi-server ./server
  - docker build -t amrit/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push amrit/multi-client
  - docker push amrit/multi-worker
  - docker push amrit/multi-nginx
  - docker push amrit/multi-server
